<a href="https://colab.research.google.com/github/wooihaw/ECE3066_T2120/blob/main/Chapter_2/Chapter_2_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ECE3066 Artificial Intelligence Systems and Applications

## Chapter 2 Part 1

### Slide 16

In [1]:
# A list is a collection of items in a specific order
alist = [57, 4.6, 'Hello', -7.5, 'world']

# A dictionary holds information in pairs of data called key-value pairs.
adict = {'name': 'Tan', 'age':45}

In [60]:
# Check the data type of the variables
print(type(alist), type(adict))

<class 'list'> <class 'dict'>


### Slide 17

In [61]:
# assign the integer value 3 to variable a
a = 3
# assign the decimal value 4.0 to variable b
b = 4.0
# assign the string 'Abc123' to variable c
c = 'Abc123'

In [62]:
print(type(a), type(b), type(c))
print(a.__sizeof__())  # check the size (in bytes) of the variable

<class 'int'> <class 'float'> <class 'str'>
28


### Slide 18

In [63]:
# Python supports multiple assignments:
a = b = 0
c, d = -3.4, 5 + 6j
c, d = d, c

# To determine the data type of a variable:
print(type(a))
print(type(c))
print(type(d))

# To convert between data types:
a = 5
b = float(a)
c = str(a)
d = int(23.4)

<class 'int'>
<class 'complex'>
<class 'float'>


### Slide 21

In [64]:
# Using format method:
a, b, c = 6, 'apples', 1.5
print('{} {} cost ${:.2f}'.format(a, b, c))

# Using f-string for string formatting (Python 3.6 and above):
a, b, c = 6, 'apples', 1.5
print(f'{a} {b} cost ${c:.2f}')

6 apples cost $1.50
6 apples cost $1.50


### Slide 23

In [1]:
mark = 51
if mark >= 50:
    print("You passed the test!")
else:
    print("You failed the test!")

a = "Passed" if mark>=50 else "Failed"

You passed the test!


### Slide 24

In [2]:
mark = 51
if mark >= 70:
    print("You scored an 'A'!")
elif mark >= 60:
    print("You scored a 'B'!")
elif mark >= 50:
    print("You scored a 'C'!")
else:
    print("You failed the test!")

You scored a 'C'!


### Slide 25

In [3]:
range(5)
range(1, 11)
range(2, 10, 2)

range(2, 10, 2)

### Slide 26

In [4]:
# To print the numbers from 0 to 9:
for i in range(10):
    print(i)
    
# To print even number from 2 to 8:
i = 0
while i < 10:
    i += 2
    print(i)

0
1
2
3
4
5
6
7
8
9
2
4
6
8
10


### Slide 27

In [5]:
# Using a loop to generate a list of square numbers:
squares = []
for i in range(1, 11):
    squares.append(i**2)
    
# Using list comprehension to generate the same list:
squares = [i**2 for i in range(1, 11)]

# Using list comprehension to capitalize the first alphabet of the names in a list:
names = ['ali', 'bala', 'chan', 'david']
cap_names = [n.capitalize() for n in names]
print(cap_names)

['Ali', 'Bala', 'Chan', 'David']


### Slide 30

In [8]:
# Read and store the contents of a file as a string:
with open('atext.txt', 'r') as f:
    astring = f.read() # including newline character
print(astring)

This is line 1.
This is line 2.
This is line 3.


In [9]:
# Read one line of a file and store it as a string:
with open('atext.txt', 'r') as f:
    astring2 = f.readline()  # including newline character
print(astring2)

This is line 1.



In [10]:
# Read and store the contents of a file as a list of lines:
with open('atext.txt', 'r') as f:
    alist = f.readlines() # including newline character
print(alist)

['This is line 1.\n', 'This is line 2.\n', 'This is line 3.']


### Slide 31

In [11]:
# Write a string to a file:
astring = 'ECE3066 Artificial Intelligence Systems and Applications'
with open('atext.txt', 'w') as f:
    f.write(astring) # newline character is not appended

In [13]:
alist = ['Line 1\n', 'Line 2\n', 'Line 3\n']
# Write a list to a file:
with open('atext.txt', 'w') as f:
    f.writelines(alist)  # newline character is not appended

### Slide 40

In [2]:
import numpy as np
# Create a NumPy array from a Python list
array = np.array([1, 2, 3])
print(array)

[1 2 3]


In [3]:
alist = [1, 2, 3]  # Python list
print(2 * alist)

[1, 2, 3, 1, 2, 3]


In [4]:
print(2 * array)

[2 4 6]


In [5]:
# Create a 5-integer array filled with zeros
a = np.zeros(5, dtype=int)
print(a)

[0 0 0 0 0]


In [6]:
# Create a 3x2 floating-point array filled with 1s
b = np.ones((3, 2), dtype=float)
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [7]:
# Create a 2x3 array filled with 3.14
c = np.full((2, 3), 3.14)
print(c)

[[3.14 3.14 3.14]
 [3.14 3.14 3.14]]


### Slide 41

In [8]:
import numpy as np
# Create an array filled with linear sequence
# Starting at 0, ending at 3, stepping by 0.5
d = np.arange(0, 3, 0.5)
print(d)

[0.  0.5 1.  1.5 2.  2.5]


In [9]:
# Create an array of 5 values evenly spaced from 0 to 1
e = np.linspace(0, 1, 5)
print(e)

[0.   0.25 0.5  0.75 1.  ]


In [11]:
# Create a 3x3 array of uniformly distributed random
# values between 0 and 1
f = np.random.random((3, 3))
print(f)

[[0.94202929 0.87569415 0.18728438]
 [0.95843607 0.31290576 0.97378391]
 [0.67169342 0.36626613 0.4123    ]]


### Slide 42

In [12]:
import numpy as np
# Create a 2x3 array of random integers in interval [0, 10)
x = np.random.randint(0, 10, (2, 3))
print(x)

[[0 5 7]
 [7 8 9]]


In [13]:
print(x.ndim)    # dimensionality
print(x.shape)   # shape of array
print(x.size)    # number of element

2
(2, 3)
6


In [14]:
print(x[0, 1])   # element at row 0, column 1

print(x[1, -1])  # element at row 1, last column (column 2)

print(x[1, :])   # elements at row 1

print(x[:, -1])  # elements at last column (column 2)

print(x[:2, 1:]) # elements at row 0-1, column 1-2

5
9
[7 8 9]
[7 9]
[[5 7]
 [8 9]]


### Slide 43

In [15]:
import numpy as np
# Create a 10-integer array from 0 to 9
y = np.arange(0, 10)
print(y)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
# Reshape to a 2x5 array
print(y.reshape(2, 5))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [19]:
# Reshape to an array with 5 rows
# number of columns will be automatically calculated
print(y.reshape(5, -1))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


### Slide 44

In [1]:
import numpy as np
z = np.arange(0, 6).reshape(2, 3)
print(z)

[[0 1 2]
 [3 4 5]]


In [2]:
# Stack arrays vertically
aa = np.vstack([z, z])
print(aa)

[[0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]]


In [3]:
# Stack arrays horizontally
print(np.hstack([z, z]))

[[0 1 2 0 1 2]
 [3 4 5 3 4 5]]


In [4]:
# Split array vertically
upper, lower = np.vsplit(aa, [1])
print(upper)

[[0 1 2]]


In [5]:
# Split array horizontally
left, right = np.hsplit(aa, [2])
print(right)

[[2]
 [5]
 [2]
 [5]]


### Slide 47

In [6]:
import pandas as pd

step_data = [3620, 7891, 9761, 3907, 4338, 5373]

step_counts = pd.Series(step_data, name='steps')

print(step_counts) 

0    3620
1    7891
2    9761
3    3907
4    4338
5    5373
Name: steps, dtype: int64


In [7]:
# Add a date range to the Series
step_counts.index = pd.date_range('20150329', periods=6)

print(step_counts)

2015-03-29    3620
2015-03-30    7891
2015-03-31    9761
2015-04-01    3907
2015-04-02    4338
2015-04-03    5373
Freq: D, Name: steps, dtype: int64


### Slide 48

In [8]:
# Just like a dictionary
print(step_counts['2015-04-01'])
# Or by index position--like an array
print(step_counts[3])

3907
3907


In [9]:
# Select all of April
print(step_counts['2015-04'])

2015-04-01    3907
2015-04-02    4338
2015-04-03    5373
Freq: D, Name: steps, dtype: int64


### Slide 49

In [10]:
import numpy as np
# View the data type
print(step_counts.dtypes)

int64


In [11]:
# Convert to a float
step_counts = step_counts.astype(np.float)

# View the data type
print(step_counts.dtypes)

float64


### Slide 50

In [12]:
# Create invalid data
step_counts[1:3] = np.NaN
print(step_counts)

# Now fill it in with zeros
step_counts = step_counts.fillna(0.)
# equivalently, 
# step_counts.fillna(0., inplace=True)

print(step_counts[1:3])

2015-03-29    3620.0
2015-03-30       NaN
2015-03-31       NaN
2015-04-01    3907.0
2015-04-02    4338.0
2015-04-03    5373.0
Freq: D, Name: steps, dtype: float64
2015-03-30    0.0
2015-03-31    0.0
Freq: D, Name: steps, dtype: float64


### Slide 51

In [13]:
# Step data
step_data = [3620, 7891, 9761, 3907, 4338, 5373]

# Cycling distance
cycling_data = [10.7, 0, None, 2.4, 15.3, 10.9, 0, None]

# Create a tuple of data
joined_data = list(zip(step_data, cycling_data))

# The dataframe
activity_df = pd.DataFrame(joined_data)

print(activity_df)

      0     1
0  3620  10.7
1  7891   0.0
2  9761   NaN
3  3907   2.4
4  4338  15.3
5  5373  10.9


### Slide 52

In [14]:
# Add column names to dataframe
activity_df = pd.DataFrame(joined_data, 
                           index=pd.date_range('20150329', 
                                               periods=6), 
                           columns=['Walking','Cycling'])

print(activity_df)

            Walking  Cycling
2015-03-29     3620     10.7
2015-03-30     7891      0.0
2015-03-31     9761      NaN
2015-04-01     3907      2.4
2015-04-02     4338     15.3
2015-04-03     5373     10.9


### Slide 53

In [15]:
# Select row of data by index name
print(activity_df.loc['2015-04-01'])

Walking    3907.0
Cycling       2.4
Name: 2015-04-01 00:00:00, dtype: float64


In [16]:
# Select row of data by integer position
print(activity_df.iloc[-3])

Walking    3907.0
Cycling       2.4
Name: 2015-04-01 00:00:00, dtype: float64


### Slide 54

In [17]:
# Dictionary approach
print(activity_df['Walking'])

2015-03-29    3620
2015-03-30    7891
2015-03-31    9761
2015-04-01    3907
2015-04-02    4338
2015-04-03    5373
Freq: D, Name: Walking, dtype: int64


In [18]:
# Object-oriented approach
print(activity_df.Walking)

2015-03-29    3620
2015-03-30    7891
2015-03-31    9761
2015-04-01    3907
2015-04-02    4338
2015-04-03    5373
Freq: D, Name: Walking, dtype: int64


### Slide 55

In [ ]:
# First column (Column 0)
print(activity_df.iloc[:,0])

### Slide 56

In [ ]:
# The location of the data file
filepath = 'data/iris_data.csv'
# Import the data
data = pd.read_csv(filepath)

# Print a few rows 
print(data.iloc[:5])

### Slide 57

In [ ]:
# Create a new column that is a product 
# of both measurements
data['sepal_area'] = data.sepal_length * data.sepal_width

# Print a few rows and columns
print(data.iloc[:5, -3:])

### Slide 58

In [ ]:
# The lambda function applies what 
# follows it to each row of data
data['abbrev'] = (data
                 .species
                 .apply(lambda x:
                        x.replace('Iris-','')))
# Note that there are other ways to 
# accomplish the above

print(data.iloc[:5, -3:])

### Slide 59

In [ ]:
# Concatenate the first two and 
# last two rows
small_data = pd.concat([data.iloc[:2], data.iloc[-2:]])
print(small_data.iloc[:,-3:])

### Slide 60

In [ ]:
# Use the size method with a 
# DataFrame to get count
# For a Series, use the .value_counts 
# method
group_sizes = (data.groupby('species').size())

print(group_sizes)

### Slide 61

In [ ]:
# Mean calculated on a DataFrame
print(data.mean())

In [ ]:
# Median calculated on a Series
print(data.petal_length.median())

In [ ]:
# Mode calculated on a Series
print(data.petal_length.mode())

In [ ]:
# Standard dev, and variance on a series 
print(data.petal_length.std(),
      data.petal_length.var())     

### Slide 62

In [ ]:
# Print statistical description
print(data.describe())

### Slide 63

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(-np.pi, np.pi, 50)
y_sin = np.sin(x)
y_cos = np.cos(x)

plt.plot(x, y_sin, 'r*-', label= 'sin')
plt.plot(x, y_cos, 'bo-', label= 'cos')
plt.xlabel('x coordinates')
plt.ylabel('y coordinates')
plt.title('A Matplotlib example')
plt.legend(loc='best')
plt.grid(axis='both')
plt.show()

### Slide 64

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Use a fixed random seed number
np.random.seed(42)

pts = np.random.randint(0, 20, (10, 2))

plt.scatter(pts[:, 0], pts[:, 1], color='b', marker='*')
plt.xlabel('x-coord')
plt.ylabel('y-coord')
plt.title('A Matplotlib scatterplot example')
plt.grid(axis='both')
plt.show()

### Slide 64

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Use a fixed random seed number
np.random.seed(42)

values = np.random.randint(0, 20, 100)
bins_1 = np.arange(0, 21)

plt.hist(values, color='b', bins=bins_1)
plt.xlabel('Values')
plt.ylabel('Frequency of occurrence')
plt.title('A Matplotlib histogram example')
plt.xticks(range(0, 20))
plt.grid(axis='y')
plt.show()

In [ ]:
import matplotlib.pyplot as plt

x = ['A', 'B', 'C', 'F']
y = [21, 42, 29, 8]

plt.bar(x, y, color=['b', 'g', 'g', 'r'])
plt.xlabel('Grade')
plt.ylabel('No. of students')
plt.title('Summary of results')
plt.show()

### Slide 67

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(-np.pi, np.pi, 25)
y_sin = np.sin(x)
y_cos = np.cos(x)

plt.subplot(2, 1, 1)
plt.plot(x, y_sin, 'r.-')
plt.title('Sine')

plt.subplot(2, 1, 2)
plt.plot(x, y_cos, 'b^-')
plt.title('Cosine')

plt.tight_layout()
plt.show()